version: "3.8"
services:
  front-envoy:
    build:
      context: ./front-envoy
      dockerfile: Dockerfile
    networks:
    - envoymesh
    ports:
    - "8080:8080"
  weather-forecast:
    build:
      context: ./service
      dockerfile: Dockerfile
    networks:
    - envoymesh
networks:
  envoymesh: {}