version: "3.8"
services:
  front-envoy:
    build:
      context: ./front-envoy
      dockerfile: Dockerfile
    networks:
    - envoymesh
    ports:
    - "8080:8080"
    - "8001:8001"
  discovery-a:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        FOLDER: POCAPIDiscoveryA
    networks:
    - envoymesh
    environment:
      - SERVICE_NAME=a
      - SOLUTION=POCAPIDiscoveryA.dll
  discovery-b:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        FOLDER: POCAPIDiscoveryB
    networks:
    - envoymesh
    environment:
      - SERVICE_NAME=b
      - SOLUTION=POCAPIDiscoveryB.dll
  discovery-c:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        FOLDER: POCAPIDiscoveryC
    networks:
    - envoymesh
    environment:
      - SERVICE_NAME=c
      - SOLUTION=POCAPIDiscoveryC.dll
networks:
  envoymesh: {}